apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-login
  namespace: nginx
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
       app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: minjunun/ik:v1130
        name: web-login
