apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-login
  namespace: nginx
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
       app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: 548021806095.dkr.ecr.ap-northeast-2.amazonaws.com/login-ecr:login20
        name: web-login
