apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: nginx
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
       app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: 548021806095.dkr.ecr.ap-northeast-2.amazonaws.com/test-ecr:main8
        name: web-nginx
